# directory where to save results (dataset csvs, checkpoints, logs, etc)
output_dir: null  # must be provided as CLI arg
# simsamu dir with .srt and .wav files
simsamu_dir: null  # must be provided as CLI arg
# directory of checkpoint to finetune, with model weights and tokenizer file
pretrained_dir: null  # must be provided as CLI arg

# for debugging purposes
max_nb_samples: null
train_on_valid: False

nb_epochs: 5
lr_asr: 0.01
lr_wav2vec2: 0.0002
ckpt_interval_minutes: 15

max_batch_length: 100
nb_batch_buckets: 30
batch_ordering: random
nb_data_workers: 6

spec_augment_speeds: [95, 100, 110]

# modules params (must be consistent with pretrained model)
nb_tokens: 500
blank_index: 0
sample_rate: 16000
wav2vec2_hub: LeBenchmark/wav2vec2-FR-7K-large
wav2vec_output_dim: 1024
nb_enc_neurons: 1024
enc_drop_out: 0.25

## modules

tokenizer: !new:sentencepiece.SentencePieceProcessor

wav2vec2: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
    source: !ref <wav2vec2_hub>
    output_norm: True
    freeze: False
    save_path: !ref <output_dir>/wav2vec2_checkpoint

enc: !new:speechbrain.nnet.containers.Sequential
    input_shape: [null, null, !ref <wav2vec_output_dim>]
    linear1: !name:speechbrain.nnet.linear.Linear
        n_neurons: !ref <nb_enc_neurons>
        bias: True
    bn1: !name:speechbrain.nnet.normalization.BatchNorm1d
    activation: !new:torch.nn.LeakyReLU
    drop: !new:torch.nn.Dropout
        p: !ref <enc_drop_out>
    linear2: !name:speechbrain.nnet.linear.Linear
        n_neurons: !ref <nb_enc_neurons>
        bias: True
    bn2: !name:speechbrain.nnet.normalization.BatchNorm1d
    activation2: !new:torch.nn.LeakyReLU
    drop2: !new:torch.nn.Dropout
        p: !ref <enc_drop_out>
    linear3: !name:speechbrain.nnet.linear.Linear
        n_neurons: !ref <nb_enc_neurons>
        bias: True
    bn3: !name:speechbrain.nnet.normalization.BatchNorm1d
    activation3: !new:torch.nn.LeakyReLU

ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <nb_enc_neurons>
    n_neurons: !ref <nb_tokens>

decoding_function: !name:speechbrain.decoders.ctc_greedy_decode

# optimizers and schedulers
asr_optimizer: !name:torch.optim.Adadelta
    lr: !ref <lr_asr>
    rho: 0.95
    eps: 1.e-8

wav2vec2_optimizer: !name:torch.optim.Adam
    lr: !ref <lr_wav2vec2>

asr_scheduler: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr_asr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

wav2vec2_scheduler: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr_wav2vec2>
    improvement_threshold: 0.0025
    annealing_factor: 0.9
    patient: 0

# pretraining
asr_model: !new:torch.nn.ModuleList
    - [!ref <enc>, !ref <ctc_lin>]

# pretrainer
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    loadables:
        tokenizer: !ref <tokenizer>
        wav2vec2: !ref <wav2vec2>
        enc: !ref <enc>
        ctc_lin: !ref <ctc_lin>
    paths:
        tokenizer: !ref <pretrained_dir>/tokenizer.ckpt
        wav2vec2: !ref <pretrained_dir>/wav2vec2.ckpt
        enc: !ref <pretrained_dir>/enc.ckpt
        ctc_lin: !ref <pretrained_dir>/ctc_lin.ckpt
